### ISSUE TITLE
ray 1 ray 2 are missing 

### ISSUE THREAD

**Issue by jxchen01** [MMV-Lab/3D-Cell-Viewer#24]
the parameters of ray 1 and ray 2 are missing

**Comment by Adrian-Sebuliba** [comment]
These are missing because they are not functional, I had to remove them. For some reason, the library includes these controls, but they simply don't work. Even in both the hosted and local versions from the Allen Institute, they remain non-functional. I'm not sure why they haven't removed these settings from the library. Perhaps certain conditions need to be met to activate them, but I haven’t been successful in getting them to work—even on their hosted demo version of the 3D visualizer, which uses the same volume-viewer library.

**Comment by Adrian-Sebuliba** [comment]
> this is not correct. It worked for me in your previous version. They only work when using path trace.
> 
> So, actually, there is new feature request. Can we only show the options "Density" and "Ray 1 ray 2" when "path trace" is selected?

I see, thank you for pointing that out. It didn’t occur to me to enable path trace first—my oversight. I’ll go ahead and reintroduce those options and ensure they are only displayed when "path trace" is selected.

**Comment by jxchen01** [comment]
sky light is not necessary

Jianxu
________________________________
